changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - feat
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - fix
        - bug
    - title: "🧰 Maintenance"
      labels:
        - chore
        - refactor
        - ci
        - build
        - test
    - title: "📝 Documentation"
      labels:
        - docs
        - documentation
    - title: "⬆️ Dependencies"
      labels:
        - dependencies
